### PR TITLE
Optimize & fix docker grading

### PR DESCRIPTION
**Pull request by fritterhoff**
Hello 😀 
there have been some minor issues using the provided setup.sh and I would like to provide a fix:
 - Because the otter-grader base image is an ubuntu 20.04 texlive-generic-recommended is replaced by texlive-plain-generic 
 - Use wkhtmltox_0.12.6-1.focal_amd64.deb instead of wkhtmltox_0.12.6-1.bionic_amd64.deb
 - Installing libcurl4-gnutls-dev and libcurl4-openssl-dev at once causes conflicts. 
 - You can reduce the layers while building the docker image by merging the commands in the Dockerfile

### CODE REVIEW

**Comment by fritterhoff** [comment]
Any idea why the tests are failing? The log messages look fine for me?

**Comment by fritterhoff** [comment]
> 
> 
> Any idea why the tests are failing? The log messages look fine for me?

Ok got the problem and fixed it in the last commit.

**Comment by fritterhoff** [comment]
Ok. I recognized that gradescope does use ubuntu 18.04 so the setup.sh needs to be kept on the old ubuntu version - sorry for the confusion

**Comment by fritterhoff** [comment]
Hi @chrispyles 
I wanted to ask if there is any interest on the changes 😀?

**Comment by chrispyles** [comment]
Hi @fritterhoff -- thanks for the PR and sorry for the delay! These changes look great, so as long as the CI passes, I'll merge this shortly.

**Comment by fritterhoff** [comment]
Hi @chrispyles,

thanks for the feedback. I'll try to fix the CI/test issues as soon as possible :)

**Comment by chrispyles** [comment]
@fritterhoff I think the issue is that the two files below need to be updated to match the new setup.sh template:

* https://github.com/fritterhoff/otter-grader/blob/docker-grading/test/test-assign/rmd-autograder-correct/setup.sh
* https://github.com/fritterhoff/otter-grader/blob/docker-grading/test/test-assign/gs-autograder-correct/setup.sh

**Comment by fritterhoff** [comment]
Thanks for the hint :) These files must be changed and also the `run_autograder` ... already working on it ;)

**Pull request merged**
