### PR TITLE
Customizable output paths for Otter Generate

### LINKED ISSUE #401: custom names for autograder.zip files
Could otter assign use custom names for the autograder.zip files, e.g. use the notebook name as a prefix and the date and time as a suffix? This could avoid confusion while I develop multiple assignments

### PR DESCRIPTION
**Pull request by chrispyles**
As titled. Also includes an update to Otter Assign which changes the name of the generated autograder zip file to `{notebook stem}-autograder_{timestamp}.zip`.

Closes #401

### CODE REVIEW

**Comment by chrispyles** [comment]
@fritterhoff it looks like builds on this branch have started failing due to something related to buildkit. Do you have any idea what's going on here? https://github.com/ucbds-infra/otter-grader/runs/3642222139#step:5:168

**Comment by chrispyles** [comment]
Update on the build issues: this seems to be a known issue with the GHA cache for buildx. https://github.com/docker/buildx/issues/681

**Comment by champoll** [comment]
Just to clarify, how do I use this? When I run "otter assign" on my notebook, the output still contains a file named autograder.zip

**Comment by chrispyles** [comment]
@champoll This fix is part of v3.2.0, which has not yet been released. If you want to use it, you will need to install the development version of Otter from GitHub.

**Pull request merged**
