### PR TITLE
Update notebook_format.rst

### PR DESCRIPTION
**Pull request by taylorgibson**
Fixing comments for assignment metadata for Otter Assign Format v1

### CODE REVIEW

**Comment by chrispyles** [comment]
The part of the file you're generating is automatically-generated when the documentation is built so any changes to its source will just get overwritten when readthedocs runs. I think this is probably an issue with the logic that's used to generate this YAML. It's created [here](https://github.com/ucbds-infra/otter-grader/blob/master/docs/conf.py#L234) based on [this object](https://github.com/ucbds-infra/otter-grader/blob/master/otter/assign/assignment.py#L10) using [this function](https://github.com/ucbds-infra/otter-grader/blob/master/otter/utils.py#L188). Feel free to fix it if you've got the time, otherwise I'll take a look at it later.

**Review by chrispyles — CHANGES_REQUESTED** [review]
See my comment.

**Comment by taylorgibson** [comment]
Thanks @chrispyles . Looking at the docs it looks like the issue stems from the `seed` section, as that's where the descriptions get off from their associated keys. It looks like there was *not* an issue with the subkeys generated in the `export_cell` section. Here's the relevant code:

```
{
        "key": "export_cell",
        "description": "whether to include an Otter export cell in the output notebooks",
        "default": [
            {
                "key": "instructions",
                "description": "additional submission instructions to include in the export cell",
                "default": "",
            },
            {
                "key": "pdf",
                "description": "whether to include a PDF of the notebook in the generated zip file",
                "default": True,
            },
            {
                "key": "filtering",
                "description": "whether the generated PDF should be filtered",
                "default": True,
            },
            {
                "key": "force_save",
                "description": "whether to force-save the notebook with JavaScript (only works in " \
                    "classic notebook)",
                "default": False,
            },
            {
                "key": "run_tests",
                "description": "whether to run student submissions against local tests during export",
                "default": False,
            },
        ],
    },
    {
        "key": "seed",
        "description": "intercell seeding configurations",
        "default": None,
        "subkeys": [
            {
                "key": "variable",
                "description": "a variable name to override with the autograder seed during grading",
                "default": None,
            },
            {
                "key": "autograder_value",
                "description": "the value of the autograder seed",
                "default": None,
            },
            {
                "key": "student_value",
                "description": "the value of the student seed",
                "default": None,
            },
        ],
    },
```

Since `export_cell` appears to work as intended I used that as a reference. Based on what's there, I'm thinking that just dropping `subkeys` from `seed` and moving that dictionary it contains to the `default` key (as done with the `export_cell` section) would correct the issue. For better or for worse it would avoid finding the issue with the `subkey` logic in `utils.py`.

I'll make the necessary changes and update the PR.

**Comment by taylorgibson** [comment]
I made what I think are fixing changes to `assignment.py` and reverted my changes to `notebook_format.rst`. I hope it ends up being helpful. Thanks for the guidance on where to look! Let me know if there's anything I can do to help.

**Review by chrispyles — CHANGES_REQUESTED** [review]
Can you run `make docs` and commit the results so we can see that it correctly updates the rst files?

**Comment by taylorgibson** [comment]
Hi @chrispyles  I've run `make docs` and committed the results. Looking at the html on my local computer appears to confirm that the changes have fixed the issue.

**Comment by taylorgibson** [comment]
Hi @chrispyles  It loos like one of the tests is failing, I assume it's related to the changes I made.
```
======================================================================
FAIL: test_r_example (test.test_assign.TestAssign)
Checks that otter assign works for R notebooks correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/otter-grader/test/test_assign.py", line 92, in test_r_example
    self.assertDirsEqual(TEST_FILES_PATH + "output", TEST_FILES_PATH + "r-correct",
  File "/home/otter-grader/test/__init__.py", line 99, in assertDirsEqual
    self.assertDirsEqual(f1, f2, ignore_ext=ignore_ext, ignore_dirs=ignore_dirs,
  File "/home/otter-grader/test/__init__.py", line 99, in assertDirsEqual
    self.assertDirsEqual(f1, f2, ignore_ext=ignore_ext, ignore_dirs=ignore_dirs,
  File "/home/otter-grader/test/__init__.py", line 77, in assertDirsEqual
    self.assertFilesEqual(dir1, dir2)
  File "/home/otter-grader/test/__init__.py", line 49, in assertFilesEqual
    self.assertEqual(c1, c2, f"Contents of {p1} did not equal contents of {p2}")
AssertionError: '{\n  "seed": null,\n  "seed_variable": null,\n  "lang": "r"\n}' != '{\n  "lang": "r"\n}'
  {
-   "seed": null,
-   "seed_variable": null,
    "lang": "r"
  } : Contents of test/test-assign/output/autograder/otter_config.json did not equal contents of test/test-assign/r-correct/autograder/otter_config.json
```
It does seem like since it's related to `seed` and `seed_variable`, which are parts of the dictionary that I changed in `assignment.py` that it's very likely a result of what I did, although since I don't have a great understanding of what else is going on with the otter-grader codebase on a larger scale it could just be a coincidence. Happy to keep helping or just let you take it from here, whatever you think is best.

**Comment by chrispyles** [comment]
Hi @taylorgibson -- sorry for the delay. Been busy lately and this fell through the cracks. Yes, it does appear that the failing check is related to the changes you made. It looks like there are two keys in the `otter_config.json` that shouldn't be there after these changes. If you've got time feel free to debug this, otherwise I'll try to get to it later.

**Comment by chrispyles** [comment]
These changes are obsolete since Otter is now using `fica` to generate these blocks in the documentation, so I'm going to close this.

**Pull request closed without merging**
